version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_started
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - TZ=Europe/Madrid
    volumes:
      - ./backend:/app
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql_agenda
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_agenda_smart
      TZ: Europe/Madrid
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
